SERVICE_PROVIDER = "AUTH_PROVIDER"
USERNAME = "YOUR_EMAIL"
PASSWORD = "YOUR_PASSWORD"

DATABASE = "database.sqlite"

BOT_API_TOKEN = 'YOU_BOT_API_TOKEN'


# Delay between gym scans
GYM_SCAN_DELAY = 1

ENCRYPT_LIB_PATH = "ENCRYPT_LIBRARY_PATH"
